service: pizza-order-processing

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole

functions:
  processOrder:
    handler: handler.process_order
    events:
      - s3:
          bucket: pizzaria2-fiap
          event: s3:ObjectCreated:*
          rules:
            - prefix: em-preparacao/
      - s3:
          bucket: pizzaria2-fiap
          event: s3:ObjectCreated:*
          rules:
            - prefix: pronto/

  sendToPreparationQueue:
    handler: handler.send_to_preparation_queue
    events:
      - sqs:
          arn:
            Fn::Join:
              - ":"
              - - "arn:aws:sqs"
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - "sqs-preparacao"

  sendToReadyQueue:
    handler: handler.send_to_ready_queue
    events:
      - sqs:
          arn:
            Fn::Join:
              - ":"
              - - "arn:aws:sqs"
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - "sqs-pronto"

  insertIntoDynamoDBPreparation:
    handler: handler.insert_into_dynamodb_preparation
    events:
      - sqs:
          arn:
            Fn::Join:
              - ":"
              - - "arn:aws:sqs"
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - "sqs-preparacao"

  insertIntoDynamoDBReady:
    handler: handler.insert_into_dynamodb_ready
    events:
      - sqs:
          arn:
            Fn::Join:
              - ":"
              - - "arn:aws:sqs"
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - "sqs-pronto"
                
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pizzaria2-fiap

    SQSPreparacao:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqs-preparacao

    SQSPronto:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqs-pronto

    DynamoDBTablePreparacao:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pedidos-preparacao
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    DynamoDBTablePronto:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pedidos-pronto
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
